### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by Ladvace** [kazeraniman/FlappyBirdClone#1]
Does it work if exported to mobile, I mean does the touch work instead of the click?

**Comment by kazeraniman** [comment]
Great question!  I spent a little time digging into some project settings to allow this and it seems like it now works after changing one setting!  I also took the chance to fix the display on mobile devices so it should now look passable.  You also gave me an excuse to update the project to Godot 3.1 (and to fix a bug which was introduced as a result 😄) so I appreciate it.

Please keep in mind that I tested this on an android emulator so I'm not entirely sure how it would work if exported to an actual device, but hopefully the theory is sound and it should work regardless.  

Let me know if you have any other questions and I'll do my best to address them!  If not, please let me know and I'll close this issue.

**Comment by kazeraniman** [comment]
There hasn't been a follow-up here for a while, so I'll close this for now.  Please feel free to open up another issue if you have any more questions!
